version: '3'

services:
  licensingservice:
    image: ostock/organization-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
       - "SPRING_CLOUD_CONFIG_URI = http://configserver:8071"
       